### ISSUE TITLE
404 Not found

### ISSUE THREAD

**Issue by mananraheja** [black-shadows/Cracking-the-Coding-Interview#1]
The book is no longer there

**Comment by FahimFBA** [comment]
We can access the books now. Can you please check the links again and submit the feedback.

**Comment by Cyrusroy001** [comment]
the link is working now

**Comment by jbanahan** [comment]
The link is not working for me. Seems to be intermittent based on the previous comments.

https://github.com/black-shadows/Cracking-the-Coding-Interview/blob/f438e1843d0383dc52f0f3519d165b937a0b11fc/Book/Link%20to%20the%20Book.txt#L3

**Comment by black-shadows** [comment]
Please check the below link:
https://www.mediafire.com/file/douu4hiq1sfz1pn/Cracking+the+Coding+Interview+189+Programming+Questions+and+Solutions.pdf/file
(Its working perfectly fine)
Also I've update it in my repo.
@jbanahan @mananraheja

**Comment by jbanahan** [comment]
@black-shadows That link works, the one prior to your edit does not. Thank you!
